### ISSUE TITLE
Add chromedriver to package.json

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/wp-e2e-webdriver#21]
@gedex is there a reason why `chromedrive` is a prerequisite that needs to be installed separately instead of being a dependency that is included in the `package.json` file? If we add it to `package.json` we can control the version that is used and don't need to worry about people installing an incompatible version.

**Comment by gedex** [comment]
@rodrigoprimo IIRC, when I started this the binary provided by npm package was left behind with chromedriver and causing some tests failed. I assumed you're referring to https://www.npmjs.com/package/chromedriver?

> What this is really doing is just grabbing a particular "blessed" (by this module) version of ChromeDriver. As new versions are released and vetted, this module will be updated accordingly.

If the npm package is updated with the version that's stable enough for our tests (this repo and other dependents), I'm fine with it.

**Comment by gedex** [comment]
@rodrigoprimo https://github.com/Automattic/wp-e2e-tests is not including chromedriver as dependency too. I believe they've a good reason for that /cc @alisterscott

**Comment by laurendavissmith** [comment]
If we wanted to go down this path and not rely on an external package it would not be difficult to to have a little js script run on `postinstall` that grabs the binary zip that we specify (https://chromedriver.storage.googleapis.com/index.html?path=2.33/), unzip it and place the chromedriver binary into the node_modules/.bin folder

**Comment by gedex** [comment]
@laurendavissmith that works for me too.

@rodrigoprimo Maybe we can try the npm package first and see if it works locally and in travis container. For travis, we still do [`apt-get`](https://github.com/woocommerce/wp-e2e-webdriver/blob/master/.travis.yml#L8) and that needs to be updated as well. If it's causing trouble then we can try @laurendavissmith suggestion. Also, it should runs in Linux and Windows as well.

**Comment by rodrigoprimo** [comment]
Thanks for the explanation @gedex. I wasn't aware that there were issues in the past with the npm package for chromedriver. I have been using it since I started working on WC e2e tests last week and it is working fine. It seems that they are regularly updated now, the version available on npm matches the one on the chromedriver site.

Before moving forward with this, I will wait to hear @alisterscott input as I don't have any previous experience with the tools we are using.

I like @laurendavissmith suggestion if using the npm package is not an option for some reason, but this is not a priority to me so I probably won't implement the script to manually download ` chromedriver` from the site.

**Comment by alisterscott** [comment]
Hi, I didn't actually realize you can get Chomedriver via npm

For our WP.com e2e tests we use CircleCI which either has it preinstalled (Circle v1) or specified as for the docker container (Circle v2) and locally we mostly use Macs so use Homebrew to install it.

But using npm makes sense as then it's all managed and contained in the project.

I'd try to use the npm package and see if it works on locally and in Travis and if so 👍 

cc @hoverduck @bsessions85: can we do this as well?

**Comment by bsessions85** [comment]
I have played around with this a little bit and it works fine. The only issue I have seen is when trying to run tests in a docker container with my local directories mapped to the container. The tests will fail, presumably because the linux docker container is trying to use chromedriver made for mac. Running  `npm uninstall chromedriver` followed by `npm install` should fix it in that situation.

**Comment by hoverduck** [comment]
Thanks for the suggestion, this was great!  We enabled it in wp-e2e-tests with https://github.com/Automattic/wp-e2e-tests/pull/774

**Comment by rodrigoprimo** [comment]
Thanks everyone for your comments. I will create a PR to install chromedriver via npm.
